[tool.uv.workspace]
members = ["services/*", "shared"]

[dependency-groups]
dev = [
    "grpcio>=1.76.0",
    "grpcio-tools>=1.76.0",
    "httpx>=0.28.1",
    "pipreqs>=0.5.0",
    "protobuf>=6.33.1",
    "pytest>=9.0.1",
    "pytest-asyncio>=1.3.0",
    "websockets>=15.0.1",
]

[tool.uv]
index = [
    { name = "pytorch-cpu", url = "https://download.pytorch.org/whl/cpu", explicit = true }
]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]
